Repository Step3-kakao-tech-campus/Team10_FE_USER, pull requests merged in 2023-10, with the labels that each got.

#16 전남대_10조_뽀득뽀득_4주차
  .eslintrc.cjs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/sprint-backlog.md
  .gitignore
  .storybook/main.js
  .storybook/preview.js
  README.md
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/bdbd.svg
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/components/atoms/Bottomsheet.jsx
  src/components/atoms/Bottomsheet.stories.js
  src/components/atoms/Button.jsx
  src/components/atoms/Button.stories.js
  src/components/atoms/Input.jsx
  src/components/atoms/Input.stories.js
  src/components/molecules/LoginForm.jsx
  src/index.css
  src/main.jsx
  src/pages/SignupPage.jsx
  src/stories/Configure.mdx
  src/stories/Header.jsx
  src/stories/Header.stories.js
  src/stories/Page.jsx
  src/stories/Page.stories.js
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/header.css
  src/stories/page.css
  tailwind.config.js
  vite.config.js
Labels: Request Review

#29 fix: conflict
  package-lock.json
  package.json
  src/App.jsx
  src/pages/CarwashDetailPage.jsx
Labels: Type: Bug

#48 Feat/bay selection
  public/StoreInfo/Map.svg
  public/StoreInfo/Tel.svg
  public/StoreInfo/Time.svg
  src/App.jsx
  src/components/atoms/BayItem.jsx
  src/components/atoms/KeywordReview.jsx
  src/components/atoms/StoreInfo.jsx
  src/components/atoms/TabReview.jsx
  src/components/molecules/DatePicker.jsx
  src/components/molecules/DurationPicker.jsx
  src/components/molecules/TimePicker.jsx
  src/components/templates/BaySelectionTemplate.jsx
  src/components/templates/ScheduleTemplate.jsx
  src/pages/BaySelectionPage.jsx
  src/pages/SchedulePage.jsx
Labels: Priority: High, Type: Component

#68 Feat/mswmocking
  src/components/atoms/Badge.jsx
  src/components/atoms/DualBottomsheet.jsx
  src/components/atoms/TabReview.jsx
  src/components/molecules/BadgeSet.jsx
  src/components/templates/CarwashDetailTemplate.jsx
  src/components/templates/ReviewPostTemplate.jsx
  src/mocks/apis/carwahses_introduction.js
  src/mocks/apis/carwashes_bays.js
  src/mocks/apis/carwashes_introduction.js
  src/mocks/apis/carwashes_reviews.js
  src/mocks/apis/carwashes_search.js
  src/mocks/apis/reservation_currentstatus.js
  src/mocks/apis/reservations_currentstatus.js
  src/mocks/apis/reservations_payment.js
  src/mocks/apis/reservations_recent.js
  src/mocks/apis/reviews.js
  src/mocks/handlers.js
  src/pages/HomePage.jsx
  src/pages/ReservationPage.jsx
Labels: Type: Function

#72 Feat/ msw로 모킹한 데이터 페이지에 적용하기
  package-lock.json
  package.json
  src/apis/carwashes.js
  src/apis/instance.js
  src/apis/reservations.js
  src/components/templates/BaySelectionTemplate.jsx
  src/components/templates/ReservationHistroyTemplate.jsx
  src/main.jsx
Labels: Type: Enhancement, Type: Function

#76 전남대_10조_뽀득뽀득_7주차
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  package-lock.json
  package.json
  src/App.jsx
  src/apis/carwashes.js
  src/apis/instance.js
  src/apis/reservations.js
  src/components/atoms/Badge.jsx
  src/components/atoms/BayItem.jsx
  src/components/atoms/DualBottomsheet.jsx
  src/components/atoms/TabReview.jsx
  src/components/atoms/TimeSlot.jsx
  src/components/molecules/BadgeSet.jsx
  src/components/molecules/BayItem.jsx
  src/components/molecules/DatePicker.jsx
  src/components/molecules/DurationPicker.jsx
  src/components/molecules/TimePicker.jsx
  src/components/organisms/BayList.jsx
  src/components/templates/BaySelectionTemplate.jsx
  src/components/templates/CarwashDetailTemplate.jsx
  src/components/templates/PaymentTemplate.jsx
  src/components/templates/ReservationHistroyTemplate.jsx
  src/components/templates/ReviewPostTemplate.jsx
  src/components/templates/ScheduleTemplate.jsx
  src/main.jsx
  src/mocks/apis/carwahses_introduction.js
  src/mocks/apis/carwashes_bays.js
  src/mocks/apis/carwashes_introduction.js
  src/mocks/apis/carwashes_reviews.js
  src/mocks/apis/carwashes_search.js
  src/mocks/apis/reservation_currentstatus.js
  src/mocks/apis/reservations_currentstatus.js
  src/mocks/apis/reservations_payment.js
  src/mocks/apis/reservations_recent.js
  src/mocks/apis/reviews.js
  src/mocks/handlers.js
  src/pages/HomePage.jsx
  src/pages/PaymentPage.jsx
  src/pages/ReservationPage.jsx
Labels: Request Review

#77 feat: Mock API 재구현
  package-lock.json
  package.json
  src/App.jsx
  src/apis/carwashes.js
  src/apis/instance.js
  src/apis/reservations.js
  src/apis/user.js
  src/components/atoms/Button.jsx
  src/components/atoms/DistanceFromHere.jsx
  src/components/atoms/GNB.jsx
  src/components/atoms/Input.jsx
  src/components/atoms/Star.jsx
  src/components/atoms/TextInput.jsx
  src/components/molecules/CarwashCard.jsx
  src/components/organisms/LoginForm.jsx
  src/components/templates/HomeTemplate.jsx
  src/hooks/useGeoLocation.js
  src/mocks/apis/carwashes_bays.js
  src/mocks/apis/carwashes_introduction.js
  src/mocks/apis/carwashes_nearby.js
  src/mocks/apis/carwashes_reviews.js
  src/mocks/apis/carwashes_search.js
  src/mocks/apis/reservations.js
  src/mocks/apis/reservations_currentstatus.js
  src/mocks/apis/reservations_payment.js
  src/mocks/apis/reservations_recent.js
  src/mocks/apis/reviews.js
  src/mocks/handlers.js
  src/pages/HomePage.jsx
  src/pages/LoginPage.jsx
  src/pages/ReservationListPage.jsx
  src/pages/ReservationPage.jsx
Labels: Priority: Medium, Type: Function
